name: Ahyan Live Streamer

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'https://archive.org/download/facebook-1781669299225-640p_202606/Facebook_1781669299225%28640p%29.mp4'
        required: true
      stream_key:
        description: 'wway-tfmf-q95u-a74e-78mh'
        required: true

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Streaming
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          ffmpeg -re -i "${{ github.event.inputs.video_url }}" \
          -c:v libx264 -preset veryfast -b:v 2500k -maxrate 2500k -bufsize 5000k \
          -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -ac 2 -ar 44100 \
          -f flv rtmp://a.rtmp.youtube.com/live2/${{ github.event.inputs.stream_key }}
